apiVersion: apps/v1
kind: Deployment
metadata:
    name: movie-service
spec:
    replicas: 1
    selector:
    matchLabels:
        app: movie-service
    template:
    metadata:
        labels:
        app: movie-service
    spec:
        containers:
        - name: movie-service
        image: arsobhan/movie-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        
       
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
    ports:
    - name: "movie-service"
      targetPort: 8081
      port: 8081
      nodePort: 30205
      protocol: TCP
    selector:
      app: movie-service
    type: NodePort
